[tool.pytest.ini_options]

DJANGO_SETTINGS_MODULE = "bulbControl.settings"

addopts = "-rP -v -p no:warnings --cov=./bulbControlFrontend --no-cov-on-fail --cov-report=html:test_logs/cov.html -n auto"

django_debug_mode = "false"

python_files = "tests.py test_*.py *_tests.py"

log_file_date_format = "%Y-%m-%d %H:%M:%S"
log_file_level = "DEBUG"
log_file_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_file = "./test_logs/pytest-logs.log"

log_cli_level = "DEBUG"
log_cli_format = "%(asctime)s [%(levelname)8s] %(message)s (%(filename)s:%(lineno)s)"
log_cli_date_format = "%Y-%m-%d %H:%M:%S"
log_cli = "true"

minversion = "8.3.4"

required_plugins = "pytest-django>=4.9.0 pytest-cov>=6.0.0 pytest-xdist>=3.6.1"

testpaths = [
    "tests",
]

[tool.black]
line-length = 100
