name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  job1:
    name: Build 

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
        os: [ubutnu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          python -m pip install --upgrade pip
          cat ${workspaceFolder}/requirements.txt | sed -e '/^\\s*#.*$/d' -e '/^\\s*$/d' | xargs -n 1 ${workspaceFolder}/env/bin/pip3 install; if [ $? -eq 123 ]; then echo 'Running on linux pyaudiowpatch cannot be installed, do not be alarmed by the error'; fi
        elif ["$RUNNER_OS" == "Windows" ]; then
          Foreach ($package in (Get-Content -Path ${workspaceFolder}/requirements.txt)) { ${workspaceFolder}/env/Scripts/pip.exe install $package }
        fi
    - name: Run Tests
      run: |
        pytest 
