name: Django CI
permissions: write-all
on:
    push:
        branches: ['main']
    pull_request:
    schedule:
        - cron: '0 0 * * *' # Every day at midnight UTC
    workflow_dispatch:

jobs:
    build_and_test:
        name: Build and Test

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                python-version: [3.11, 3.12]
                os: [ubutnu-latest, windows-latest]

        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              id: dependencies
              run: |
                  sudo apt install portaudio19-dev
                  python -m pip install --upgrade pip
                  cat ./requirements.txt | sed -e '/^\\s*#.*$/d' -e '/^\\s*$/d' | xargs -n 1 python -m pip install || true 
                  playwright install --with-deps
            - name: Run Migrations
              id: run_migrations
              run: |
                  python manage.py makemigrations bulb_control_frontend --noinput 
                  python manage.py migrate --noinput --run-syncdb
            - name: Lint
              id: lint
              run: |
                  pylint ./ | tee pylint.txt
                  score=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)
                  echo "Pylint score was $score"
                  anybadge --value=$score --file=public/pylint.svg pylint
            - name: Run Tests
              id: run_tests
              run: |
                  pytest -s
            - name: Creating coverage folder
              run: |
                  mkdir -p coverage
            - name: Coverage Badge
              uses: tj-actions/coverage-badge-py@v1.8
              with:
                  output: coverage/coverage.svg
            - name: Publish coverage report to coverage-badge branch
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  branch: cov-badge
                  folder: coverage
