name: Django CI

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  job1:
    name: Build

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.11, 3.12]
        os: [ubutnu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        id: dependencies
        run: |
          sudo apt install portaudio19-dev
          python -m pip install --upgrade pip
          cat ./requirements.txt | sed -e '/^\\s*#.*$/d' -e '/^\\s*$/d' | xargs -n 1 python -m pip install || true
      - name: Run Tests
        id: run_tests
        run: |
          pytest

      - name: Coverage Output
        run: |
          coverage report -m

      - name: 'Make badge'
        uses: schneegans/dynamic-badges-action@v1.4.0
        with:
          # GIST_TOKEN is a GitHub personal access token with scope "gist".
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: 882115926
          filename: covbadge.json
          label: Coverage
          message: ${{ env.total }}%
          minColorRange: 50
          maxColorRange: 90
          valColorRange: ${{ env.total }}
