name: Django CI

on:
    push:
        branches: ['main']
    pull_request:
    schedule:
        - cron: '0 0 * * *' # Every day at midnight UTC
    workflow_dispatch:

jobs:
    build_and_test:
        name: Build and Test

        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                python-version: [3.11, 3.12]
                os: [ubutnu-latest, windows-latest]

        steps:
            - name: Checkout repo and submodules
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python-version }}
            - name: Install Dependencies
              id: dependencies
              run: |
                  sudo apt install portaudio19-dev
                  python -m pip install --upgrade pip
                  cat ./requirements.txt | sed -e '/^\\s*#.*$/d' -e '/^\\s*$/d' | xargs -n 1 python -m pip install || true 
                  pip install https://github.com/bboe/coveralls-python/archive/github_actions.zip
                  playwright install --with-deps
            - name: Run Migrations
              id: run_migrations
              run: |
                  python manage.py makemigrations bulb_control_frontend --noinput 
                  python manage.py migrate --noinput --run-syncdb
            - name: Run Tests
              id: run_tests
              run: |
                  coverage run --source wizlight-music-sync --module pytest
            - env:
                  COVERALLS_PARALLEL: true
                  COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN}}
              name: Submit to Coveralls
              run: coveralls
    coveralls:
        name: Get Coverage Report
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            max-parallel: 4
            matrix:
                python-version: [3.11, 3.12]
                os: [ubutnu-latest, windows-latest]
        needs: build_and_test
        steps:
            - name: Coveralls Finished
              uses: coverallsapp/github-action@master
              with:
                  github-token: ${{ secrets.GITHUB_TOKEN}}
                  parallel-finished: true
